package main

import (
	"encoding/csv"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

// These expected values were measured by executing the supplied Amiga program,
// not generated by the JS or Go implementations. See original-routine-emulation.md.
func originalMeasurements(t *testing.T, name, header string, count, inputs int) [][]int {
	t.Helper()
	file, err := os.Open("../docs/" + name + ".csv")
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	records, err := csv.NewReader(file).ReadAll()
	if err != nil {
		t.Fatal(err)
	}
	if len(records) != count+1 || strings.Join(records[0], ",") != header {
		t.Fatalf("invalid reference corpus %s", name)
	}
	seen := map[string]bool{}
	rows := make([][]int, 0, count)
	for _, record := range records[1:] {
		key := strings.Join(record[:inputs], ",")
		if seen[key] {
			t.Fatalf("duplicate reference input %s", key)
		}
		seen[key] = true
		row := make([]int, len(record))
		for i, cell := range record {
			row[i], err = strconv.Atoi(cell)
			if err != nil {
				t.Fatal(err)
			}
		}
		rows = append(rows, row)
	}
	return rows
}
func TestOriginalSustainMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-sustain", "speed,sustain,instructions", 151, 1) {
		if r[2] != 7 || actionSustain(r[0]) != r[1] {
			t.Fatalf("speed %d: got %d, original %d", r[0], actionSustain(r[0]), r[1])
		}
	}
}

func TestOriginalPredictionMeasurements(t *testing.T) {
	const unit = 22.4 / 576
	for _, r := range originalMeasurements(t, "original-prediction", "intelligence,x,y,dx,dy,targetX,targetY", 8575, 5) {
		x, z := predictedTarget(float64(576-r[2])*unit, float64(r[1]-320)*unit, -float64(r[4])*unit*25, float64(r[3])*unit*25, r[0])
		a, b := int(math.Round(z/unit+320)), int(math.Round(576-x/unit))
		if a != r[5] || b != r[6] {
			t.Fatalf("prediction %v: got %d,%d, original %d,%d", r[:5], a, b, r[5], r[6])
		}
	}
}

func TestOriginalEnemyMeasurements(t *testing.T) {
	const unit = 22.4 / 576
	for _, r := range originalMeasurements(t, "original-enemy", "team,intelligence,distance,flags,x,dx,selected", 1080, 6) {
		s := initial()
		team, intelligence, flags := r[0], r[1], r[3]
		i, base := team*9+3, (1-team)*9
		s.Period = team + 1
		s.logicalView = [2]int{0, 484}
		s.Players[i].X, s.Players[i].Z = 0, (120-320)*unit
		s.Players[i].Stats[7] = intelligence
		var distances [18]int
		for j := range distances {
			distances[j] = 999
		}
		for j := 0; j < 9; j++ {
			p := &s.Players[base+j]
			p.X, p.Z, p.moveX, p.moveZ, p.Stun = 0, (180-320)*unit, 0, 0, 1
			if j == 1 {
				p.Stun = 0
			}
			if j == 0 {
				p.Z = float64(r[4]-320) * unit
				p.moveZ = float64(r[5]) * unit * 25
				p.Stun = 0
				if flags&16 != 0 {
					p.Stun = 1
				}
				if flags&64 != 0 {
					p.X = (576 - 450) * unit
				}
			}
		}
		distances[base], distances[base+1] = r[2], 199
		x, z, ok := s.aggressionTarget(i, &distances, 0)
		if r[6] < 0 {
			if ok {
				t.Fatalf("unexpected target for %v", r)
			}
			continue
		}
		p := s.Players[base+r[6]]
		a, b := predictedTarget(p.X, p.Z, p.moveX, p.moveZ, intelligence)
		if !ok || math.Abs(x-a) > 1e-9 || math.Abs(z-b) > 1e-9 {
			t.Fatalf("enemy selection %v: got %v,%v,%v, expected %v,%v", r, x, z, ok, a, b)
		}
	}
}
func TestOriginalDistanceMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-distance", "dx,dz,distance,instructions", 6400, 2) {
		got := referenceDistance(float64(r[0])*terrainUnit, float64(r[1])*terrainUnit)
		if r[3] < 1 || r[3] > 32 || got != r[2] {
			t.Fatalf("delta %d,%d: got %d, original %d", r[0], r[1], got, r[2])
		}
	}
}
func TestOriginalPointDistanceMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-point-distance", "sprite,dx,dz,origin,distance", 9477, 3) {
		p := Player{physicalSprite: r[0]}
		if physicalPoseData.Origins[r[0]][1] != r[3] {
			t.Fatalf("sprite %d origin differs", r[0])
		}
		got := playerPointDistance(&p, float64(r[1])*terrainUnit, float64(r[2])*terrainUnit)
		if got != r[4] {
			t.Fatalf("sprite %d delta %d,%d: got %d, original %d", r[0], r[1], r[2], got, r[4])
		}
	}
}
func TestOriginalTackleMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-tackle", "attack,defense,angle,slide,jump,keeper,threshold", 4096, 6) {
		p := Player{Stats: defaultStats(), FX: 1, Action: 7}
		p.Stats[1] = r[0]
		if r[3] != 0 {
			p.Action = 1
		}
		q := Player{Stats: defaultStats(), FX: math.Round(math.Cos(float64(r[2]) * math.Pi / 4)), FZ: math.Round(math.Sin(float64(r[2]) * math.Pi / 4))}
		q.Stats[2] = r[1]
		if r[4] != 0 {
			q.Action = 2
			q.jumping = true
		}
		got := tackleThreshold(&p, &q, r[5] != 0)
		if got != r[6] {
			t.Fatalf("input %v: got %d, original %d", r[:6], got, r[6])
		}
	}
}

func TestOriginalDamageMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-damage", "power,stamina,energy,base,remaining,agr,att,def,spd,thr,pow,sta,int", 1536, 4) {
		s := initial()
		p, q := &s.Players[7], &s.Players[16]
		p.Stats[5] = r[0]
		for a := range q.Stats {
			q.Stats[a] = r[3]
		}
		q.Stats[6] = r[1]
		q.Health = float64(r[2]) * 100 / 128
		if !s.damage(7, 16) {
			t.Fatal("missing damage")
		}
		if math.Abs(q.Health-float64(r[4])*100/128) > 1e-9 {
			t.Fatalf("input %v: energy mismatch %v", r[:4], q.Health)
		}
		for a, v := range q.Stats {
			if v != r[5+a] {
				t.Fatalf("input %v: stat %d got %d original %d", r[:4], a, v, r[5+a])
			}
		}
	}
}

func TestOriginalRandomMeasurements(t *testing.T) {
	var s State
	for _, r := range originalMeasurements(t, "original-random", "seed0,seed1,step,value,state0,state1", 1536, 3) {
		if r[2] == 0 {
			s.RNG = [2]uint32{uint32(r[0]), uint32(r[1])}
		}
		got := s.randomByte()
		if got != r[3] || s.RNG != [2]uint32{uint32(r[4]), uint32(r[5])} {
			t.Fatalf("seed %v step %d: got %d state %v", r[:2], r[2], got, s.RNG)
		}
	}
}
