package main

import (
	"encoding/csv"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

// These expected values were measured by executing the supplied Amiga program,
// not generated by the JS or Go implementations. See original-routine-emulation.md.
func originalMeasurements(t *testing.T, name, header string, count, inputs int) [][]int {
	t.Helper()
	file, err := os.Open("../docs/" + name + ".csv")
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	records, err := csv.NewReader(file).ReadAll()
	if err != nil {
		t.Fatal(err)
	}
	if len(records) != count+1 || strings.Join(records[0], ",") != header {
		t.Fatalf("invalid reference corpus %s", name)
	}
	seen := map[string]bool{}
	rows := make([][]int, 0, count)
	for _, record := range records[1:] {
		key := strings.Join(record[:inputs], ",")
		if seen[key] {
			t.Fatalf("duplicate reference input %s", key)
		}
		seen[key] = true
		row := make([]int, len(record))
		for i, cell := range record {
			row[i], err = strconv.Atoi(cell)
			if err != nil {
				t.Fatal(err)
			}
		}
		rows = append(rows, row)
	}
	return rows
}
func TestOriginalSustainMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-sustain", "speed,sustain,instructions", 151, 1) {
		if r[2] != 7 || actionSustain(r[0]) != r[1] {
			t.Fatalf("speed %d: got %d, original %d", r[0], actionSustain(r[0]), r[1])
		}
	}
}
func TestOriginalDistanceMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-distance", "dx,dz,distance,instructions", 6400, 2) {
		got := referenceDistance(float64(r[0])*terrainUnit, float64(r[1])*terrainUnit)
		if r[3] < 1 || r[3] > 32 || got != r[2] {
			t.Fatalf("delta %d,%d: got %d, original %d", r[0], r[1], got, r[2])
		}
	}
}
func TestOriginalPointDistanceMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-point-distance", "sprite,dx,dz,origin,distance", 9477, 3) {
		p := Player{physicalSprite: r[0]}
		if physicalPoseData.Origins[r[0]][1] != r[3] {
			t.Fatalf("sprite %d origin differs", r[0])
		}
		got := playerPointDistance(&p, float64(r[1])*terrainUnit, float64(r[2])*terrainUnit)
		if got != r[4] {
			t.Fatalf("sprite %d delta %d,%d: got %d, original %d", r[0], r[1], r[2], got, r[4])
		}
	}
}
func TestOriginalTackleMeasurements(t *testing.T) {
	for _, r := range originalMeasurements(t, "original-tackle", "attack,defense,angle,slide,jump,keeper,threshold", 4096, 6) {
		p := Player{Stats: defaultStats(), FX: 1, Action: 7}
		p.Stats[1] = r[0]
		if r[3] != 0 {
			p.Action = 1
		}
		q := Player{Stats: defaultStats(), FX: math.Round(math.Cos(float64(r[2]) * math.Pi / 4)), FZ: math.Round(math.Sin(float64(r[2]) * math.Pi / 4))}
		q.Stats[2] = r[1]
		if r[4] != 0 {
			q.Action = 2
			q.jumping = true
		}
		got := tackleThreshold(&p, &q, r[5] != 0)
		if got != r[6] {
			t.Fatalf("input %v: got %d, original %d", r[:6], got, r[6])
		}
	}
}
