import "./style.css";
import { start } from "./controller.js";
document.querySelector("#app").innerHTML = `
<div class="arena-backdrop"><div class="viewport" id="viewport"><div class="scoreboard"><span class="team cyan">IRON VIPERS <small><span id="homeName">HOME</span></small></span><strong id="score0">00</strong><div class="clock"><span id="timer">01:30</span><small id="period">EXHIBITION</small></div><strong id="score1">00</strong><span class="team orange">STEEL JACKALS <small><span id="awayName">AWAY</span></small></span></div><div class="arena-label"><span>01 / THE FOUNDRY</span><small>INDUSTRIAL DIVISION</small></div><div id="loading">LOADING ARENA…</div><div class="result hidden" id="result"></div><div class="live-label"><i></i><span id="status">READY FOR KICKOFF</span></div><span class="asset-tag">ORIGINAL BLENDER ASSETS ↗</span></div></div>
<div class="lobby-shell" id="lobbyShell">
  <div class="lobby-topline"><span><i class="dot"></i> THE FOUNDRY / NEO ROTTERDAM</span><button id="sound">SOUND OFF</button></div>
  <main class="game-lobby">
    <div class="lobby-heading"><p class="league-label">NEON LEAGUE</p><h1>SPEEDBALL<span>Ⅱ</span></h1><p class="lobby-tagline">BRUTAL SPORT. STEEL RULES.</p></div>
    <div class="lobby-identity"><label for="name">PLAYER ID</label><input id="name" maxlength="20" placeholder="Your player name" value="Challenger" autocomplete="nickname"><span>9 VS 9 <b>/</b> 2 × 90 SECONDS</span></div>
    <div class="match-options">
      <button class="match-option training-option" id="practice"><span class="option-meta">01 / SOLO</span><strong>TRAINING <span>↗</span></strong><small>Hit the court. Take on the AI.</small></button>
      <button class="match-option host-option" id="create"><span class="option-meta">02 / ONLINE</span><strong>CREATE MATCH <span>↗</span></strong><small>Your arena. Your rival. Share a room code.</small></button>
      <form class="match-option join-option" id="joinForm"><div><span class="option-meta">03 / INVITED?</span><h2>JOIN MATCH</h2><small>Enter your rival’s six-character code.</small></div><div class="join"><input id="room" maxlength="6" placeholder="ROOM CODE" aria-label="Room code" autocomplete="off" spellcheck="false"><button id="join" type="submit">JOIN →</button></div></form>
    </div>
    <div class="lobby-message"><p id="notice" role="status">Choose your match. Own the arena.</p><div class="room-share hidden" id="roomShare"></div></div>
    <div class="lobby-bottom"><button id="howToPlay">HOW TO PLAY <span>↗</span></button><span><kbd>WASD</kbd> MOVE <kbd>SPACE</kbd> ACTION <kbd>SHIFT</kbd> TACKLE</span></div>
  </main>
  <div class="lobby-footer"><span>EXHIBITION SERIES <b>/</b> SEASON 01</span><span>NO MERCY. JUST SPORT.</span></div>
</div>
<dialog id="rules" class="lobby-rules" aria-labelledby="rulesTitle"><button id="closeRules" aria-label="Close instructions">CLOSE ×</button><h2 id="rulesTitle">Welcome to the arena</h2><p>Move with WASD or the arrow keys. You control the available player nearest the ball; eight teammates support you. Run over the ball to collect it. Tap Space for a low throw in your facing direction. Hold Space through the short wind-up to launch a lob automatically. E starts a high throw with the same short wind-up. Without the ball, Space jumps for a nearby high ball; otherwise it punches when standing still or slides when moving. Shift punches when standing still and slides when moving. Aim diagonally to bank shots off the walls.</p><p>Goals score 10 points. Wall stars and court domes score 2 points; a complete bank earns another 10 on the next bonus clock pulse and then clears. Opponents can extinguish a star first to cancel that bonus and subtract 2 points. Throw a low ball lengthwise into a side loop to build your scoring multiplier. Opposing trips remove one level before building their own multiplier. Teams switch ends after 90 seconds; the highest score after two halves wins.</p><h3>POWER-UPS &amp; INJURIES</h3><p>Run over a token to activate it. Freeze, reverse controls, weaken, boost, manic, slow, goal lock and shield last six seconds. Ball magnet, ball transport to your designated forward, full energy and zap work immediately. Zap knocks down opponents within a fixed area that follows the ball; a wider display does not extend its reach. Temporary effects end when teams prepare for a new ball launch. Freeze appears in multiplayer only. The HUD shows the active effect. Equipment improves one attribute until you take a hit; coins award 100 credits. New coins stop appearing once both teams have collected 2,000 credits; training uses a 10,000-credit limit for you. Coins already on the court remain available.</p><p>Low balls entering any of the four warp-gates emerge from the opposite wall. The two electro-bounces charge the ball so it can knock opponents down. A shield protects against the electroball when catching, but a keeper performing a block dive can still be hit.</p><p>Hits drain energy. At zero energy the player is injured: the match clock stops while medics carry them off. The opponent scores 10 points, including any multiplier. Each team has a rotating bench of three substitutes. The first substitute enters and the injured player returns to the back of the bench with reduced attributes; substitutions do not exhaust the bench.</p><p>Training runs locally. For multiplayer, create an arena and share the room code. The match starts when both players connect.</p></dialog>
<div hidden><span id="mode"></span><span id="connection"></span><span id="metrics"></span><button id="fullscreen"></button></div>`;

start();
