import "./style.css";
import { start } from "./controller.js";
document.querySelector("#app").innerHTML = `
<header><a class="brand" href="/" aria-label="Speedball home"><span class="brandmark">S<span>Ⅱ</span></span><span>SPEEDBALL<small>NEON LEAGUE</small></span></a><nav><button class="nav active" data-page="arena">DE ARENA</button><button class="nav" data-page="how">SPELREGELS</button></nav><span class="build"><i></i> BROWSER EDITION <b>01.00</b></span></header>
<main><div class="eyebrow"><span>BRUTAL SPORT. NIEUWE REGELS.</span><span>EST. 2091 / NEO ROTTERDAM</span></div><section class="title"><div><h1>HARDER. SNELLER.<br><em>SPEEDBALL.</em></h1><p>Staal tegen staal. Team tegen team. De arena wacht.</p></div><div class="season"><span>EXHIBITION SERIES</span><strong>SEASON <b>01</b></strong><span>9 TEGEN 9 &nbsp; / &nbsp; 2 × 90 SECONDEN</span></div></section>
<div class="layout"><section class="arena-card"><div class="arena-top"><span><i class="dot"></i> <span id="mode">ARENA PREVIEW</span></span><span>THE FOUNDRY <b>◆</b> NEO ROTTERDAM</span><button id="sound" title="Geluid aan of uit">GELUID UIT</button></div><div class="viewport" id="viewport"><div class="scoreboard"><span class="team cyan">IRON VIPERS <small><span id="homeName">HOME</span></small></span><strong id="score0">00</strong><div class="clock"><span id="timer">01:30</span><small id="period">EXHIBITION</small></div><strong id="score1">00</strong><span class="team orange">STEEL JACKALS <small><span id="awayName">AWAY</span></small></span></div><div class="arena-label"><span>01 / THE FOUNDRY</span><small>INDUSTRIAL DIVISION</small></div><div id="loading">ARENA WORDT GELADEN…</div><div class="result hidden" id="result"></div><div class="live-label"><i></i><span id="status">KLAAR VOOR DE AFTRAP</span></div><span class="asset-tag">ORIGINAL BLENDER ASSETS ↗</span></div><div class="arena-bottom"><span><i class="dot"></i> <span id="connection">LOKALE PREVIEW</span></span><span id="metrics">60 FPS TARGET &nbsp; • &nbsp; WEBGL 2</span><button id="fullscreen">VOLLEDIG SCHERM ↗</button></div></section>
<aside><div class="panel-head"><span>01</span> SPEEL JOUW WEDSTRIJD <b>↗</b></div><div class="play-panel"><div class="tabs"><button id="onlineTab" class="selected">MULTIPLAYER</button><button id="practiceTab">TRAINING</button></div><h2 id="panelTitle">Geen genade.<br>Wel een kamercode.</h2><p id="panelDescription">Daag een vriend uit. Deel je code en stap samen de arena in.</p><label for="name">JOUW SPELERSNAAM</label><input id="name" maxlength="20" placeholder="Bijv. Steelhead" value="Challenger"><button class="primary" id="create">MAAK EEN ARENA <span>↗</span></button><div class="divider"><span>OF SLUIT JE AAN</span></div><div class="join"><input id="room" maxlength="6" placeholder="KAMERCODE" aria-label="Kamercode"><button id="join" aria-label="Deelnemen">→</button></div><div class="room-share hidden" id="roomShare"></div><p id="notice" role="status" class="notice">Een-op-een online. Acht teamgenoten en automatische spelerkeuze.</p><button class="practice-link" id="practice">Eerst opwarmen? Speel tegen AI →</button></div><div class="transport"><span class="transport-icon">ϟ</span><div><strong>GEBOUWD VOOR SNELHEID</strong><p>WebTransport / HTTP/3 / QUIC</p></div><span class="tiny-dot"></span></div></aside></div>
<section class="lower"><div class="controls"><span class="section-number">02</span><div><h3>BEHEERS DE ARENA</h3><div class="keys"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> Bewegen</span><span><kbd>SPACE</kbd> Gooien / actie</span><span><kbd>SHIFT</kbd> Tackelen</span></div></div></div><div class="rule"><b>10</b><span>PUNTEN PER GOAL<small>Pak de bal. Breek door. Scoor.</small></span></div><div class="rule"><b>03</b><span>MINUTEN VOL GAS<small>De hoogste score wint.</small></span></div></section><section id="rules" class="hidden rules"><h2>Welkom in de arena</h2><p>Loop over de bal om hem te pakken. Met WASD of de pijltjestoetsen beweeg je de gemarkeerde speler. Je bestuurt automatisch de speler het dichtst bij de bal; de overige acht spelen mee. Gooi met spatie in je kijkrichting: kort indrukken is een lage worp, vasthouden en loslaten een lob. E gooit direct hoog. Zonder bal gebruik je spatie voor een sliding of om naar een hoge bal te springen. De bal kaatst tegen muren; richt schuin voor een bank shot. Druk op Shift voor een sliding, ook zonder tegenstander in de buurt. Een goal levert 10 punten op. Sterren aan de zijwanden en de twee scoredomes geven elk 2 punten. Vijf sterren samen geven 10 bonuspunten. Met de ramps verhoog je scores naar 1,5× of 2×. Na twee helften van 90 seconden wint de hoogste score.</p><p>Training werkt lokaal. Voor multiplayer maakt één speler een arena en vult de andere dezelfde kamercode in. De wedstrijd begint wanneer beide spelers verbonden zijn.</p></section></main><footer><span>SPEEDBALL <b>/</b> NEON LEAGUE</span><span>INSPIRED BY THE CLASSIC. BUILT FOR THE NEXT GENERATION.</span><span>NO MERCY. JUST SPORT. ↗</span></footer>`;

start();
